server:
  port: '8092'
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://${MYSQL_HOST:localhost}:3306/qdiligharad}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:medelma123@}
  jpa:
    properties:
      hibernate:
        dialect: ${SPRING_HIBERNATE_DIALECT:org.hibernate.dialect.MySQL8Dialect}
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: 'false'
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

management:
  endpoints:
    web:
      cors:
        allowed-origins: '*'
        allowed-methods: OPTIONS, GET, POST
        allowed-headers: '*'

logging:
  level:
    root: ${LOG_LEVEL:info}

swagger:
  enabled: ${SWAGGER_ENABLED:true}
  display:
    title: API
    description: Description API
    version: 1.0.0

external:
  system:
    user:
      xarika:
        uid: guid
        username: userName
        fullName: fullName
        email: email

service:
  binary:
    baseUrl: http://localhost:8090/api/document_binary
    upload: /upload
    get: /%s
