version: '3.8'

services:
  mysql:
    image: mysql
    container_name: qdiligharad-prod-db
    environment:
      MYSQL_ROOT_PASSWORD: medelma123@
      MYSQL_DATABASE: qdiligharad
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./src/main/resources/scripts/scripts.sql:/docker-entrypoint-initdb.d/init.sql:ro

spring-app:
  build: .
  container_name: qdiligharad-prod-app
  environment:
    SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3308/qdiligharad
    SPRING_DATASOURCE_USERNAME: root
    SPRING_DATASOURCE_PASSWORD: medelma123@
  ports:
    - "8080:8080"
  depends_on:
    - mysql

volumes:
  mysql-data:
